// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/prestontallen/servitor/internal/store"
)

// A page of the ledger, newest first.
type EventPage struct {
	// The events, newest first.
	Events []*store.LedgerEvent `json:"events"`
	// Pass as before_id to read the next older page. Set whenever the page is full (its length equals limit), so it can point at an empty page; null when the page is short.
	NextBeforeID *int `json:"next_before_id,omitempty"`
}

// Read-only queries over the servitor ledger and its read model. Writes stay
// on POST /api/events. Field names are snake_case, matching the REST JSON, so
// a client can fold either surface with the same code.
type Query struct {
}
