package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/prestontallen/servitor/internal/api"
	"github.com/prestontallen/servitor/internal/store"
)

// Ticket is the resolver for the ticket field.
func (r *arcResolver) Ticket(ctx context.Context, obj *store.ArcSummary) (*store.Card, error) {
	return loadersFrom(ctx).card(ctx, obj.ULID)
}

// Members is the resolver for the members field.
func (r *arcResolver) Members(ctx context.Context, obj *store.ArcSummary) ([]*store.Card, error) {
	l := loadersFrom(ctx)
	out := make([]*store.Card, 0, len(obj.Members))
	for _, m := range obj.Members {
		c, err := l.card(ctx, m.ULID)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, nil
}

// Ticket is the resolver for the ticket field.
func (r *eventResolver) Ticket(ctx context.Context, obj *store.LedgerEvent) (*store.Card, error) {
	return loadersFrom(ctx).card(ctx, obj.Ticket)
}

// ByActor is the resolver for the by_actor field.
func (r *hourBucketResolver) ByActor(ctx context.Context, obj *api.HourBucket) (RawJSON, error) {
	b, err := json.Marshal(obj.ByActor)
	return RawJSON(b), err
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context) ([]*store.Card, error) {
	cards, err := r.Service.Board(ctx)
	return ptrs(cards), err
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context, status []string, query *string, limit *int) ([]*store.Card, error) {
	f := store.ListFilter{Statuses: status}
	if query != nil {
		f.Query = *query
	}
	if limit != nil {
		f.Limit = *limit
	}
	cards, err := r.Service.List(ctx, f)
	return ptrs(cards), err
}

// Arcs is the resolver for the arcs field.
func (r *queryResolver) Arcs(ctx context.Context) ([]*store.ArcSummary, error) {
	arcs, err := r.Service.Arcs(ctx)
	out := make([]*store.ArcSummary, len(arcs))
	for i := range arcs {
		out[i] = &arcs[i]
	}
	return out, err
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, ref string) (*store.Card, error) {
	return loadersFrom(ctx).resolve(ctx, ref)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, since *time.Time, until *time.Time, tickets []string, arc *string, kind *string, actorType *string, beforeID *int, limit *int) (*EventPage, error) {
	n := 200
	if limit != nil {
		n = *limit
	}
	if n < 1 || n > maxEvents {
		return nil, &api.APIError{Code: "invalid_event", Message: fmt.Sprintf("limit must be 1..%d, got %d", maxEvents, n)}
	}
	f := store.LedgerFilter{Limit: n}
	if since != nil {
		f.Since = *since
	}
	if until != nil {
		f.Until = *until
	}
	if kind != nil {
		f.Kind = *kind
	}
	if actorType != nil {
		f.ActorType = *actorType
	}
	if beforeID != nil {
		f.BeforeID = int64(*beforeID)
	}
	scope, err := r.ticketScope(ctx, tickets, arc)
	if err != nil {
		return nil, err
	}
	page := &EventPage{Events: []*store.LedgerEvent{}}
	if scope != nil && len(scope) == 0 {
		return page, nil // tickets and arc share no ticket
	}
	f.Tickets = scope
	evs, err := r.Service.Events(ctx, f)
	if err != nil {
		return nil, err
	}
	for i := range evs {
		page.Events = append(page.Events, &evs[i])
	}
	if len(evs) == n {
		last := int(evs[len(evs)-1].ID)
		page.NextBeforeID = &last
	}
	return page, nil
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, since *time.Time, until *time.Time, days *int) (*api.Timeline, error) {
	q := api.TimelineQuery{Since: since, Until: until}
	if days != nil {
		q.Days = *days
	}
	tl, err := r.Service.Timeline(ctx, q)
	return &tl, err
}

// ParentTicket is the resolver for the parent_ticket field.
func (r *ticketResolver) ParentTicket(ctx context.Context, obj *store.Card) (*store.Card, error) {
	if obj.Parent == nil {
		return nil, nil
	}
	return loadersFrom(ctx).card(ctx, *obj.Parent)
}

// Children is the resolver for the children field.
func (r *ticketResolver) Children(ctx context.Context, obj *store.Card) ([]*store.Card, error) {
	l := loadersFrom(ctx)
	if err := l.index(ctx); err != nil {
		return nil, err
	}
	kids := l.children[obj.ULID]
	if kids == nil {
		kids = []*store.Card{}
	}
	return kids, nil
}

// Events is the resolver for the events field.
func (r *ticketResolver) Events(ctx context.Context, obj *store.Card, since *time.Time, until *time.Time, kind *string, limit *int) ([]*store.LedgerEvent, error) {
	k := eventsKey{limit: 100}
	if since != nil {
		k.since = *since
	}
	if until != nil {
		k.until = *until
	}
	if kind != nil {
		k.kind = *kind
	}
	if limit != nil {
		k.limit = *limit
	}
	if k.limit < 1 || k.limit > maxEvents {
		return nil, &api.APIError{Code: "invalid_event", Message: fmt.Sprintf("limit must be 1..%d, got %d", maxEvents, k.limit)}
	}
	return loadersFrom(ctx).events.load(ctx, k, obj.ULID)
}

// Aggregate is the resolver for the aggregate field.
func (r *ticketResolver) Aggregate(ctx context.Context, obj *store.Card) (RawJSON, error) {
	doc, err := r.Service.Ctx(ctx, obj.ULID)
	return RawJSON(doc), err
}

// Arc returns ArcResolver implementation.
func (r *Resolver) Arc() ArcResolver { return &arcResolver{r} }

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// HourBucket returns HourBucketResolver implementation.
func (r *Resolver) HourBucket() HourBucketResolver { return &hourBucketResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Ticket returns TicketResolver implementation.
func (r *Resolver) Ticket() TicketResolver { return &ticketResolver{r} }

type (
	arcResolver        struct{ *Resolver }
	eventResolver      struct{ *Resolver }
	hourBucketResolver struct{ *Resolver }
	queryResolver      struct{ *Resolver }
	ticketResolver     struct{ *Resolver }
)
